[project]
name = 'froggy-auction'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.Froggys]
path = 'contracts/Froggys.clar'
clarity_version = 2
epoch = 2.4

[contracts.froggy-auctions-v1]
path = 'contracts/froggy-auctions-v1.clar'
clarity_version = 2
epoch = 2.4

[contracts.micro-nthng]
path = 'contracts/micro-nthng.clar'
clarity_version = 2
epoch = 2.4

[contracts.nft-trait]
path = 'contracts/nft-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.nope]
path = 'contracts/nope.clar'
clarity_version = 2
epoch = 2.4

[contracts.sip-010-trait-ft-standard]
path = 'contracts/sip-010-trait-ft-standard.clar'
clarity_version = 2
epoch = 2.4

[contracts.wrapped-nothing-v8]
path = 'contracts/wrapped-nothing-v8.clar'
clarity_version = 2
epoch = 2.4

[repl]
clarity_wasm_mode = false
show_timings = false

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
